### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/data'

### ISSUE THREAD

**Issue by hsauod** [luanshiyinyang/FairMOT#1]
大佬你好，感谢您的分享。我想使用预训练模型，跑自己的demo video，请问需要下载mot 15/20数据集，进行data preparation之后，才可以跑demo video吗？我查看我的报错代码“PermissionError: [Errno 13] Permission denied: '/data'”，issues里说需要data preparation，但我认为不需要吧？请问大佬你下载数据集，进行data preparation了嘛？感谢您的回复

**Comment by luanshiyinyang** [comment]
这个报错只是因为你没有/data目录的访问权限

hsauod <notifications@github.com> 于2021年1月11日周一 下午10:44写道：

**Comment by luanshiyinyang** [comment]
我认为该问题已经解决，我将关闭这个issue
